# File: backend/data_engine.py
from typing import List, Dict, Any
from models import ArchitectureBlueprint, DataLayerSpec

class DataEngine:
    """
    AGENT_DATA core logic.
    Transforms data specs into Supabase-compatible SQL.
    """
    
    def generate_schema(self, spec: DataLayerSpec) -> str:
        sql_output = "-- Generated by AIOrch AGENT_DATA\n\n"
        
        # 1. Enable Extensions
        sql_output += "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";\n\n"
        
        # 2. Table Creation
        for table in spec.tables:
            name = table.get("name")
            columns = table.get("columns", [])
            
            sql_output += f"CREATE TABLE IF NOT EXISTS public.{name} (\n"
            # Add default columns for every table as per Governance
            sql_output += "    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n"
            sql_output += "    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,\n"
            sql_output += "    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,\n"
            
            # Map description-based columns to SQL
            # Simple heuristic mapping for POC
            for col in columns:
                if "name" in col.lower() or "title" in col.lower():
                    sql_output += f"    {col.split(' ')[0]} TEXT,\n"
                elif "id" in col.lower() and "uuid" in col.lower() and "primary" not in col.lower():
                    sql_output += f"    {col.split(' ')[0]} UUID,\n"
                elif "status" in col.lower():
                    sql_output += f"    {col.split(' ')[0]} TEXT DEFAULT 'pending',\n"
                else:
                    # Default fallback
                    sql_output += f"    {col.split(' ')[0]} TEXT,\n"
            
            # Trim trailing comma and newline
            sql_output = sql_output.rstrip(",\n") + "\n);\n\n"
            
            # 3. Enable RLS
            sql_output += f"ALTER TABLE public.{name} ENABLE ROW LEVEL SECURITY;\n\n"
            
        # 4. Apply Policies
        for policy in spec.rls_policies:
            # Note: This would usually be handled by a more sophisticated parser or LLM
            # For POC, we'll generate a dummy policy based on the text
            sql_output += f"-- Policy: {policy}\n"
            if "personal access" in policy.lower():
                # Extract first table name for dummy policy
                t_name = spec.tables[0]["name"]
                sql_output += f"CREATE POLICY \"Users can manage their own {t_name}\" \n"
                sql_output += f"ON public.{t_name} FOR ALL \n"
                sql_output += f"USING (auth.uid() = user_id);\n\n"
                
        return sql_output

    def generate_seed_data(self, spec: DataLayerSpec) -> str:
        sql_output = "-- Seed Data\n"
        for table in spec.tables:
            name = table.get("name")
            sql_output += f"-- INSERT INTO public.{name} (...) VALUES (...);\n"
        return sql_output

agent_data = DataEngine()
