# File: backend/data_engine.py
from typing import List, Dict, Any
from models import ArchitectureBlueprint, DataLayerSpec

class DataEngine:
    """
    AGENT_DATA core logic.
    Transforms data specs into Supabase-compatible SQL.
    """
    
    def generate_schema(self, spec: DataLayerSpec) -> str:
        sql_output = "-- Generated by AIOrch AGENT_DATA\n\n"
        
        # 1. Enable Extensions
        sql_output += "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";\n\n"
        
        # 2. Table Creation
        for table in spec.tables:
            name = table.get("name")
            columns = table.get("columns", [])
            
            sql_output += f"CREATE TABLE IF NOT EXISTS public.{name} (\n"
            # Add default columns for every table as per Governance
            sql_output += "    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n"
            sql_output += "    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,\n"
            sql_output += "    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,\n"
            
            # Map description-based columns to SQL
            # Simple heuristic mapping for POC
            for col in columns:
                if isinstance(col, dict):
                    col_name = col.get("name", "field")
                    col_text = f"{col.get('name', '')} {col.get('type', '')}".lower()
                else:
                    col_name = str(col).split(' ')[0]
                    col_text = str(col).lower()
                if "name" in col_text or "title" in col_text:
                    sql_output += f"    {col_name} TEXT,\n"
                elif "id" in col_text and "uuid" in col_text and "primary" not in col_text:
                    sql_output += f"    {col_name} UUID,\n"
                elif "status" in col_text:
                    sql_output += f"    {col_name} TEXT DEFAULT 'pending',\n"
                else:
                    sql_output += f"    {col_name} TEXT,\n"
            
            # Trim trailing comma and newline
            sql_output = sql_output.rstrip(",\n") + "\n);\n\n"
            
            # 3. Enable RLS
            sql_output += f"ALTER TABLE public.{name} ENABLE ROW LEVEL SECURITY;\n\n"
            
        # 4. Apply Policies
        for policy in spec.rls_policies:
            # Note: This would usually be handled by a more sophisticated parser or LLM
            # For POC, we'll generate a dummy policy based on the text
            sql_output += f"-- Policy: {policy}\n"
            if "personal access" in policy.lower():
                # Extract first table name for dummy policy
                t_name = spec.tables[0]["name"]
                sql_output += f"CREATE POLICY \"Users can manage their own {t_name}\" \n"
                sql_output += f"ON public.{t_name} FOR ALL \n"
                sql_output += f"USING (auth.uid() = user_id);\n\n"
                
        return sql_output

    def generate_seed_data(self, spec: DataLayerSpec) -> str:
        sql_output = "-- Seed Data\n"
        for table in spec.tables:
            name = table.get("name")
            sql_output += f"-- INSERT INTO public.{name} (...) VALUES (...);\n"
        return sql_output

    async def generate_schema_llm(self, data_layer, project_name: str, provider, models) -> str:
        """LLM-driven schema generation. Injects the blueprint data_layer and the
        AGENT_DATA contract; returns raw SQL. Caller supplies provider + model chain."""
        from agent_specs import get_spec
        from llm_client import agent_generate

        spec = get_spec("AGENT_DATA")
        context = {
            "project_name": project_name,
            "data_layer": data_layer.dict() if hasattr(data_layer, "dict") else data_layer,
        }
        instruction = (
            "Generate the complete PostgreSQL/Supabase schema (CREATE TABLE + RLS "
            "policies) for every table above. Honor the HARD RULES in your system prompt."
        )
        return await agent_generate(
            provider,
            models=models,
            system_prompt=spec["system_prompt"],
            context=context,
            instruction=instruction,
        )

agent_data = DataEngine()
