from typing import List, Dict, Any

class UIEngine:
    def generate_component(self, name: str, style_guide: Dict[str, str]) -> str:
        primary = style_guide.get("primary", "#00f3ff")
        return f"""// File: components/{name}.jsx
'use client';
import React, {{ useState }} from 'react';

export const {name} = ({{ children }}) => {{
    const [isHovered, setIsHovered] = useState(false);

    return (
        <div 
            className="component-card"
            onMouseEnter={{() => setIsHovered(true)}}
            onMouseLeave={{() => setIsHovered(false)}}
            style={{{{
                transform: isHovered ? 'translateY(-5px)' : 'translateY(0)',
                borderColor: isHovered ? '{primary}' : 'rgba(255,255,255,0.1)',
                boxShadow: isHovered ? '0 10px 30px -10px {primary}40' : 'none'
            }}}}
        >
            <div className="component-header">
                <div className="component-icon" style={{{{ color: '{primary}', backgroundColor: '{primary}15' }}}}>✨</div>
                <h3 className="component-title">{name}</h3>
            </div>
            
            <p className="component-desc">
                Interactive component generated by AIOrchBuilder. Fully wired to accept downstream data layer models.
            </p>
            
            <div className="component-content">
                {{children}}
            </div>
            
            <button 
                className="action-btn"
                style={{{{ 
                    borderColor: '{primary}', 
                    color: isHovered ? '#000' : '{primary}',
                    backgroundColor: isHovered ? '{primary}' : 'transparent'
                }}}}
                onClick={{() => alert('{name} functionality executing...')}}
            >
                Take Action
            </button>
        </div>
    );
}};
"""

    def generate_page(self, name: str, components: List[str], style_guide: Dict[str, str]) -> str:
        primary = style_guide.get("primary", "#00f3ff")
        imports = "\n".join([f"import {{ {c} }} from '../../components/{c}';" for c in components])
        
        return f"""// File: app/{name.lower()}/page.jsx
import React from 'react';
{imports}

export default function {name}Page() {{
    return (
        <main className="page-wrapper fade-in-up">
            <header className="page-header">
                <div className="tag-pill" style={{{{ color: '{primary}', borderColor: '{primary}40', backgroundColor: '{primary}10' }}}}>Intelligent Module</div>
                <h1 className="page-title">{name} Workspace</h1>
                <p className="page-subtitle">Sandbox environment for the {name} data models and interactive tools.</p>
            </header>
            
            <section className="component-grid">
                {chr(10).join([f"<{c} />" for c in components])}
            </section>
        </main>
    );
}}
"""

    def generate_package_json(self, project_name: str) -> str:
        return f"""{{
  "name": "{project_name.lower().replace(' ', '-')}-frontend",
  "version": "1.0.0",
  "private": true,
  "scripts": {{
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  }},
  "dependencies": {{
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "next": "14.2.3"
  }}
}}
"""

    def generate_dockerfile(self) -> str:
        return """FROM node:18-alpine AS deps
WORKDIR /app
COPY package.json ./
RUN npm install

FROM node:18-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:18-alpine AS runner
WORKDIR /app
ENV NODE_ENV production
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
EXPOSE 3000
CMD ["node", "server.js"]
"""

    def generate_layout(self, style_guide: Dict[str, str], pages: List[str]) -> str:
        primary = style_guide.get("primary", "#00f3ff")
        nav_links = "".join([f'<Link href="/{p.lower()}" className="nav-link">{p}</Link>' for p in pages])
        
        return f"""// File: app/layout.jsx
import Link from 'next/link';

export default function RootLayout({{ children }}) {{
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
        <style dangerouslySetInnerHTML={{{{__html: `
          :root {{ --primary: {primary}; }}
          * {{ box-sizing: border-box; }}
          body {{
            margin: 0; padding: 0;
            font-family: 'Plus Jakarta Sans', sans-serif;
            background-color: #030303;
            background-image: 
              radial-gradient(circle at 15% 50%, rgba(20, 20, 20, 0.4), transparent 25%),
              radial-gradient(circle at 85% 30%, rgba(10, 10, 10, 0.4), transparent 25%);
            color: #ededed;
            min-height: 100vh;
          }}
          
          /* Navigation */
          .top-nav {{
            position: fixed; top: 0; width: 100%; z-index: 1000;
            background: rgba(3, 3, 3, 0.7);
            backdrop-filter: blur(20px); -webkit-backdrop-filter: blur(20px);
            border-bottom: 1px solid rgba(255,255,255,0.06);
            display: flex; justify-content: space-between; align-items: center;
            padding: 1rem 5vw; height: 70px;
          }}
          .brand-logo {{
            font-size: 1.35rem; font-weight: 800; color: #fff; text-decoration: none;
            display: flex; align-items: center; gap: 0.5rem; letter-spacing: -0.02em;
          }}
          .brand-badge {{
            font-size: 0.7em; padding: 0.2rem 0.5rem; background: var(--primary); color: #000;
            border-radius: 4px; font-weight: 700; letter-spacing: 0.05em; text-transform: uppercase;
          }}
          .nav-menu {{ display: flex; gap: 2rem; }}
          .nav-link {{
            color: #888; text-decoration: none; font-size: 0.95rem; font-weight: 500;
            transition: all 0.2s; position: relative;
          }}
          .nav-link:hover {{ color: #fff; }}
          .nav-link::after {{
            content: ''; position: absolute; bottom: -24px; left: 0; width: 100%; height: 2px;
            background: var(--primary); opacity: 0; transition: opacity 0.2s;
          }}
          .nav-link:hover::after {{ opacity: 1; }}

          /* Layout Container */
          .page-wrapper {{
            max-width: 1200px; margin: 0 auto; padding: 120px 2rem 4rem 2rem;
          }}

          /* Headers */
          .page-header {{ text-align: left; margin-bottom: 4rem; max-width: 800px; }}
          .tag-pill {{
            display: inline-block; padding: 0.4rem 1rem; border-radius: 50px; font-size: 0.8rem;
            font-weight: 600; margin-bottom: 1.5rem; border: 1px solid;
          }}
          .page-title {{
            font-size: 3.5rem; font-weight: 800; line-height: 1.1; margin: 0 0 1rem 0;
            letter-spacing: -0.03em; color: #fff;
          }}
          .page-subtitle {{
            font-size: 1.2rem; color: #888; line-height: 1.6; margin: 0;
          }}

          /* Grids & Components */
          .component-grid {{
            display: grid; grid-template-columns: repeat(auto-fill, minmax(320px, 1fr)); gap: 1.5rem;
          }}
          .component-card {{
            background: rgba(255,255,255,0.02);
            border: 1px solid;
            border-radius: 16px; padding: 2rem;
            display: flex; flex-direction: column; transition: all 0.3s cubic-bezier(0.16, 1, 0.3, 1);
            backdrop-filter: blur(10px);
          }}
          .component-header {{ display: flex; align-items: center; gap: 1rem; margin-bottom: 1.2rem; }}
          .component-icon {{ width: 40px; height: 40px; border-radius: 10px; display: flex; align-items: center; justify-content: center; font-size: 1.2rem; }}
          .component-title {{ font-size: 1.25rem; font-weight: 700; margin: 0; color: #fff; }}
          .component-desc {{ color: #a0a0a0; font-size: 0.95rem; line-height: 1.6; margin: 0 0 1.5rem 0; flex: 1; }}
          .component-content {{ margin-bottom: 1.5rem; }}
          
          /* Buttons */
          .action-btn {{
            padding: 0.8rem 1.5rem; border-radius: 8px; font-weight: 600; font-size: 0.95rem;
            font-family: inherit; border: 1px solid; cursor: pointer; transition: all 0.2s;
            margin-top: auto; align-self: flex-start;
          }}

          /* Animations */
          .fade-in-up {{ animation: fadeInUp 0.7s cubic-bezier(0.16, 1, 0.3, 1) forwards; opacity: 0; transform: translateY(20px); }}
          @keyframes fadeInUp {{ to {{ opacity: 1; transform: translateY(0); }} }}
        `}}}} />
      </head>
      <body>
        <nav className="top-nav">
            <Link href="/" className="brand-logo">OrchBuilder <span className="brand-badge">OS</span></Link>
            <div className="nav-menu">
                {nav_links}
            </div>
        </nav>
        {{children}}
      </body>
    </html>
  );
}}
"""

    def generate_next_config(self) -> str:
        return """/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'standalone',
  async redirects() {
    return [
      {
        source: '/',
        destination: '/home',
        permanent: false,
      },
    ]
  },
}
module.exports = nextConfig
"""

agent_ui = UIEngine()
