// File: components/ContactForm.jsx
'use client';
import React, { useState } from 'react';

export const ContactForm = ({ children }) => {
    const [isHovered, setIsHovered] = useState(false);

    return (
        <div 
            className="component-card"
            onMouseEnter={() => setIsHovered(true)}
            onMouseLeave={() => setIsHovered(false)}
            style={{
                transform: isHovered ? 'translateY(-5px)' : 'translateY(0)',
                borderColor: isHovered ? '#00f3ff' : 'rgba(255,255,255,0.1)',
                boxShadow: isHovered ? '0 10px 30px -10px #00f3ff40' : 'none'
            }}
        >
            <div className="component-header">
                <div className="component-icon" style={{ color: '#00f3ff', backgroundColor: '#00f3ff15' }}>✨</div>
                <h3 className="component-title">ContactForm</h3>
            </div>
            
            <p className="component-desc">
                Interactive component generated by AIOrchBuilder. Fully wired to accept downstream data layer models.
            </p>
            
            <div className="component-content">
                {children}
            </div>
            
            <button 
                className="action-btn"
                style={{ 
                    borderColor: '#00f3ff', 
                    color: isHovered ? '#000' : '#00f3ff',
                    backgroundColor: isHovered ? '#00f3ff' : 'transparent'
                }}
                onClick={() => alert('ContactForm functionality executing...')}
            >
                Take Action
            </button>
        </div>
    );
};
