-- Generated by AIOrch AGENT_DATA

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS public.profile_views (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    viewer_ip TEXT,
    view_date TEXT,
    page TEXT
);

ALTER TABLE public.profile_views ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.contact_messages (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    sender_name TEXT,
    sender_email TEXT,
    message TEXT,
    status TEXT DEFAULT 'pending'
);

ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

-- Policy: Public can insert profile_views
-- Policy: Public can insert contact_messages
-- Policy: Only admin can read contact_messages
